version: "3.9"

services:
  mirofish:
    build: .
    container_name: mirofish
    restart: always
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - ZEP_API_KEY=${ZEP_API_KEY}
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.mirofish.rule=Host(`mirofish.readyai.com.br`)
      - traefik.http.routers.mirofish.entrypoints=websecure
      - traefik.http.routers.mirofish.tls=true
      - traefik.http.services.mirofish.loadbalancer.server.port=5001

networks:
  dokploy-network:
    external: true
